-- MySQL Script generated by MySQL Workbench
-- Saturday 02 November 2019 09:36:00 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema badm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema badm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `badm` DEFAULT CHARACTER SET latin1 ;
USE `badm` ;

-- -----------------------------------------------------
-- Table `badm`.`check_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `badm`.`check_list` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `create_date` VARCHAR(45) NOT NULL,
  `created_by` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `station_id` VARCHAR(45) NOT NULL,
  `station_name` VARCHAR(45) NOT NULL,
  `maintenance_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `badm`.`organizations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `badm`.`organizations` (
  `id` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `create_date` DATETIME NOT NULL,
  `created_by` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `badm`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `badm`.`projects` (
  `id` INT(5) ZEROFILL NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `manager` VARCHAR(45) NOT NULL,
  `number` INT(11) NOT NULL,
  `customer_name` VARCHAR(45) NOT NULL,
  `project_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `project_number_UNIQUE` (`project_number` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10000
DEFAULT CHARACTER SET = latin1
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `badm`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `badm`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `create_date` DATETIME NOT NULL,
  `created_by` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `badm`.`stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `badm`.`stations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `create_date` DATETIME NOT NULL,
  `created_by` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `station_id` VARCHAR(45) NULL DEFAULT NULL,
  `check_list_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC, `station_id` ASC),
  INDEX `fk_stations_check_list1_idx` (`check_list_id` ASC),
  CONSTRAINT `fk_stations_check_list1`
    FOREIGN KEY (`check_list_id`)
    REFERENCES `badm`.`check_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `badm`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `badm`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `create_date` DATE NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `is_active` CHAR(1) NOT NULL,
  `roles_id` INT(11) NOT NULL,
  `organizations_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  INDEX `fk_users_roles1_idx` (`roles_id` ASC),
  INDEX `fk_users_organizations1_idx` (`organizations_id` ASC),
  CONSTRAINT `fk_users_organizations1`
    FOREIGN KEY (`organizations_id`)
    REFERENCES `badm`.`organizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `badm`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `badm`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `badm`.`tasks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `assigned_to` VARCHAR(45) NOT NULL,
  `created_by` VARCHAR(45) NOT NULL,
  `create_date` VARCHAR(45) NOT NULL,
  `start_time` VARCHAR(45) NOT NULL,
  `end_time` VARCHAR(45) NOT NULL,
  `reassigned_to` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `station_name` VARCHAR(45) NOT NULL,
  `station_type` VARCHAR(45) NOT NULL,
  `users_id` INT(11) NOT NULL,
  `check_list_id` INT(11) NOT NULL,
  `projects_id` INT(5) ZEROFILL NOT NULL,
  PRIMARY KEY (`id`, `projects_id`),
  INDEX `fk_tasks_users1_idx` (`users_id` ASC),
  INDEX `fk_tasks_check_list1_idx` (`check_list_id` ASC),
  INDEX `fk_tasks_projects1_idx` (`projects_id` ASC),
  CONSTRAINT `fk_tasks_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `badm`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_check_list1`
    FOREIGN KEY (`check_list_id`)
    REFERENCES `badm`.`check_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `badm`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `badm`;

DELIMITER $$
USE `badm`$$
CREATE DEFINER=`bgraph`@`localhost` TRIGGER `badm`.`projects_BEFORE_INSERT` BEFORE INSERT ON `projects` FOR EACH ROW
BEGIN
SET @project_number:= ( SELECT AUTO_INCREMENT 
                        FROM INFORMATION_SCHEMA.TABLES
                        WHERE TABLE_NAME='projects'
                          AND TABLE_SCHEMA=DATABASE() ); 
      SET new.project_number= CONCAT('PN-' , 'id');
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
